### ISSUE TITLE
Minimax Optimization Elucidation

### ISSUE THREAD

**Issue by CaptainCuong** [UCSB-NLP-Chang/Fairness-Reprogramming#5]
https://github.com/UCSB-NLP-Chang/Fairness-Reprogramming/blob/35fe3b21c36aa646d25e277a9a9bf9ce4397d8df/CelebA/train.py#L267-L283

Can you explain the procedure of minimax optimization (Line278-279)?

https://github.com/UCSB-NLP-Chang/Fairness-Reprogramming/blob/35fe3b21c36aa646d25e277a9a9bf9ce4397d8df/CelebA/train.py#L278-L279

Can you explain the calculations of Line278-279?

As far as what I understand, Line275-279 is for Adversary optimization. By simple calculations, `(param.grad * unit_adversary_grad).sum() * unit_adversary_grad` has the same value of param.grad. Hence, the value of `param.grad` after Line278 is 0.

**Comment by ghzhang233** [comment]
Hello! Thanks for your interest in our work. 

`
param.grad -= (param.grad * unit_adversary_grad).sum() * unit_adversary_grad
`
This is to remove the projection of *param.grad* on *unit_adversary_grad*. For example, assume *param.grad=[1,1]* and *unit_adversary_grad=[0,1]*, then after line 278, *param.grad* would be [1, 0]. The intuition is to make sure that the utility loss gradient and fairness loss gradient are orthogonal to each other. This implementation follows _Zhang et al._ Check out the second term of equation 1 in their paper. In practice, line 278 could also be removed, and sometimes it could make training even more stable. 

Please let me know if there is anything else that I can help.

`Zhang, B. et al. “Mitigating Unwanted Biases with Adversarial Learning.” Proceedings of the 2018 AAAI/ACM Conference on AI, Ethics, and Society (2018): n. pag.`

**Comment by CaptainCuong** [comment]
Hi!

I understand. Thanks for your prompt reply.
